// Copyright 2026 CloudSmith Contributors
// SPDX-License-Identifier: Apache-2.0

using System.Text.Json.Serialization;

namespace CloudSmith.Core.Jobs;

/// <summary>
/// Base type for the canonical job dispatch wire frames exchanged on the
/// PaaS ↔ Relay WebSocket and the Relay ↔ Agent LAN hop.
/// Serialized with a <c>$type</c> JSON discriminator and camelCase property
/// names per the frozen contract (design/api-surface/job-dispatch-contract.md, AB#4839).
/// </summary>
[JsonPolymorphic(TypeDiscriminatorPropertyName = "$type")]
[JsonDerivedType(typeof(JobDispatch), "job.dispatch")]
[JsonDerivedType(typeof(JobAck), "job.ack")]
[JsonDerivedType(typeof(JobResult), "job.result")]
public abstract record JobFrame;

/// <summary>
/// <c>job.dispatch</c> frame (PaaS → Relay). Instructs a Relay to enqueue a job
/// for agent execution. <see cref="PayloadJson"/> is an opaque JSON string —
/// the dispatch pipeline never interprets it; only the executing target parses it.
/// </summary>
/// <param name="JobId">Primary key of the <c>core.jobs</c> row. Generated by the API.</param>
/// <param name="JobType">Logical operation identifier, e.g. <c>cluster.validate-network</c>. Maps to <c>core.jobs.job_type</c>.</param>
/// <param name="PayloadJson">Opaque JSON string. Content schema is owned by the module that defines the <paramref name="JobType"/>.</param>
/// <param name="IdempotencyKey">Client-supplied dedupe key; unique per <c>(org_id, idempotency_key)</c>.</param>
/// <param name="Traceparent">W3C trace context, propagated end-to-end (API → Relay → Agent → subprocess).</param>
public sealed record JobDispatch(
    [property: JsonPropertyName("jobId")]          Guid    JobId,
    [property: JsonPropertyName("jobType")]        string  JobType,
    [property: JsonPropertyName("payloadJson")]    string  PayloadJson,
    [property: JsonPropertyName("idempotencyKey")] string? IdempotencyKey = null,
    [property: JsonPropertyName("traceparent")]    string? Traceparent = null) : JobFrame;

/// <summary>
/// Acknowledgement status carried by a <see cref="JobAck"/> frame.
/// Serialized as lowercase strings on the wire.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter<JobAckStatus>))]
public enum JobAckStatus
{
    /// <summary>The Relay durably persisted the job to its local queue.</summary>
    [JsonStringEnumMemberName("accepted")] Accepted,

    /// <summary>The Relay could not accept the job; the reason is in <see cref="JobAck.Detail"/>.</summary>
    [JsonStringEnumMemberName("rejected")] Rejected,

    /// <summary>The jobId is already persisted in the Relay queue — a safe re-dispatch.</summary>
    [JsonStringEnumMemberName("duplicate")] Duplicate
}

/// <summary>
/// <c>job.ack</c> frame (Relay → PaaS). Sent when the Relay has durably persisted
/// the job to its local queue — not merely received it in memory.
/// <c>accepted</c> maps to the <c>dispatched</c> (routed) job state, not <c>running</c>.
/// </summary>
/// <param name="JobId">Echoes the dispatch.</param>
/// <param name="AckStatus">One of <c>accepted</c>, <c>rejected</c>, <c>duplicate</c>.</param>
/// <param name="Detail">Reason when <paramref name="AckStatus"/> is <see cref="JobAckStatus.Rejected"/> (e.g. unknown target agent).</param>
public sealed record JobAck(
    [property: JsonPropertyName("jobId")]     Guid         JobId,
    [property: JsonPropertyName("ackStatus")] JobAckStatus AckStatus,
    [property: JsonPropertyName("detail")]    string?      Detail = null) : JobFrame;

/// <summary>
/// <c>job.result</c> frame (Relay → PaaS). Forwarded by the Relay when the Agent
/// reports completion. Results are idempotent on <see cref="JobId"/> — the API
/// applies a result only if the job is non-terminal. Timeout adjudication is
/// API-side only: relays and agents never fabricate timeout results.
/// </summary>
/// <param name="JobId">The job the result belongs to.</param>
/// <param name="Succeeded">Authoritative success flag (<c>exitCode == 0</c> for script jobs).</param>
/// <param name="ExitCode">Process exit code; <c>-1</c> for infrastructure failures (payload missing, spawn failure).</param>
/// <param name="Output">Stdout / structured result body. May be empty, never null.</param>
/// <param name="Error">Stderr or exception message when <paramref name="Succeeded"/> is false.</param>
/// <param name="CompletedAt">Set by the Agent at completion time; persisted to <c>core.jobs.completed_at</c>.</param>
public sealed record JobResult(
    [property: JsonPropertyName("jobId")]       Guid           JobId,
    [property: JsonPropertyName("succeeded")]   bool           Succeeded,
    [property: JsonPropertyName("exitCode")]    int            ExitCode,
    [property: JsonPropertyName("output")]      string         Output,
    [property: JsonPropertyName("error")]       string?        Error,
    [property: JsonPropertyName("completedAt")] DateTimeOffset CompletedAt) : JobFrame;
